
use_frameworks!
install! 'cocoapods', :deterministic_uuids => false


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
            config.build_settings['WARNING_CFLAGS'] = '-Wno-documentation'
        end
    end
end

target "HBRouter" do
  pod 'HBRouter' , :path => '../../'  



end
