


#source 'ssh://git@gitlab.hellobike.cn:10022/Torrent/Cocoapods_StaticBinary_iOS.git'
source 'ssh://git@gitlab.hellobike.cn:10022/Torrent/Cocoapods_StaticSource_iOS.git'




use_frameworks!
install! 'cocoapods', :deterministic_uuids => false

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
            config.build_settings['WARNING_CFLAGS'] = '-Wno-documentation'
        end
    end
end

target "Example_swift" do
  pod 'HBRouter'  , :path => '../' #'0.0.1-SNAPSHOT'
  
  pod 'Business_Pod_test' , :path => '../test/'


end
